package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'CmdRun'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("CmdRun")) {
    vcs {
        remove(RelativeId("JavaSeleniumVCS"))
    }

    expectSteps {
        script {
            name = "cmd step"
            scriptContent = """echo "hello there""""
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = """
                echo "hello there"
                pwd
                echo "Another one"
            """.trimIndent()
        }
    }
}
