package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'JavaSeleniumVCS'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("JavaSeleniumVCS")) {
    val expected = GitVcsRoot({
        id("JavaSeleniumVCS")
        name = "JavaSeleniumVCS"
        url = "https://github.com/cgungaloo/JavaCucumberFramework.git"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        name = "JavaSeleniumVCS2"
    }

}
